modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/starforcraft/Botany-Pots-Tiers/issues/new/choose"
[[mods]]
modId="botanypotstiers"
version="${file.jarVersion}"
displayName="Botany Pots Tiers"
displayURL="https://www.curseforge.com/minecraft/mc-mods/botany-pots-tiers"
logoFile="examplemod.png"
credits="Thanks for downloading this mod."
authors="YTrollman"
description="This mod adds a Tiered Botany Pots."

[[dependencies.botanypotstiers]]
    modId="botanypots"
    mandatory=true
    versionRange="[7.1.,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanypotstiers]]
    modId="bookshelf"
    mandatory=true
    versionRange="[10,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.botanypotstiers]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.botanypotstiers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"